package com.mycelia.sandbox.runtime;

/**
 * The different Mycelia Runtime types.
 * 
 * There are many different type of Runtime capable of running a Mycelia application.
 * Some of these Runtimes are more suited for resource heavy application or more parallel computing application.
 * The runtime also differs in concrete node implementation.
 */
public enum ApplicationRuntimeType
{
	/**
	 * A Mycelia Runtime entirely running on the local computer where the application is started.
	 * 
	 * This runtime type uses threads for the concrete MyceliaNode instances.
	 * A memory object dispatches the Transmissions generated by the application's node
	 * immediately at the time the transmission sending method is called.
	 */
	LOCAL,
	
	/**
	 * A Mycelia Runtime spanning a computer network.
	 * 
	 * This runtime type uses a separate computer to execute each node.
	 * The computer starting the application is only used to monitor the application's
	 * execution across the network. Network packages are used to communicate between the MyceliaNodes.
	 */
	NETWORK;
}
